# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmZkMWM5OWE3ZjU1NDMzZmZlYzc4YThiOGRkZmMwY2M4ODRmNjlhMzE4ZmU0ZTg4ZTQzMDE2NGFhODg2NjlkYWFjOWE2N2M4NTAwYzU4ZmZjOTEyZjJlYzY2ZWJiMzdlZmFhOGVlOTczYzVhZWVkM2JiMzU1NmJlMzc1NTcyMzQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
